account/urls.py
from django.urls import path

from account import views

app_name = 'account'
urlpatterns = [
    path('signup', views.view_signup, name='view_signup'),
    path('login', views.view_login, name='view_login'),
    path('logout', views.view_logout, name='view_logout'),
    path('', views.view_home, name='view_home'),
]

database/urls.py
from mysite import views
from django.contrib import admin
from django.urls import include, path
from database import views


app_name = 'database'
urlpatterns = [
    path('', views.databaseHome, name='databaseHome'),
    path('health-list', views.collectHealthList, name='collectHealthList'),
    path('corpus-csv', views.corpusCSV, name='corpusCSV'),
    path('split-csv', views.splitCSV, name='splitCSV'),
    path('makeURLArray', views.makeURLArray, name='makeURLArray'),
    path('makePPString', views.makePPString, name='makePPString'),
    path('testFunction', views.testFunction, name='testFunction'),

]

mysite/urls.py
from mysite import views
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('', views.Home, name='Home'),
    path('about', views.about, name='about'),

    path('uploads/', include('uploads.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('database/', include('database.urls')),


]

uploads/templates/uploads/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url('teams/', include('teams.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#need to copy paste this back grom the github

uploads/urls.py
from django.urls import path
from . import views



app_name = 'uploads'
urlpatterns = [

    path('', views.uploadHere, name='uploadHere'),
    path('list/', views.upload_list, name='upload_list'),
    path('getFile/', views.getFile, name='getFile'),

    path('download/', views.download, name='download'),

    path('results/<str:appID>', views.results, name='results'),
    path('results/', views.results, name='results'),
    path('<int:link_id>/vote/', views.vote, name='vote'),

    path('uploadsManyAPK', views.uploadsManyAPK, name='uploadsManyAPK'),

    path('test/', views.download_JSONfile, name = 'download_JSONfile'),
    path('certDownload/', views.download_Certfile, name = 'download_Certfile'),
    path('VirusTotalDownload/', views.download_VirusTotal, name = 'download_VirusTotal'),
    path('PrivacyPolicyTextDownload/', views.download_PrivacyPolicyText, name = 'download_PrivacyPolicyText'),
    path('URLRequestsDownload/', views.download_URLRequests, name = 'download_URLRequests'),
    path('SuspiciousURLRequestsDownload/', views.download_SuspiciousURLRequests, name = 'download_SuspiciousURLRequests'),
    path('emulator/', views.emulator, name='emulator'),
    path('avd', views.avd, name='avd'),
    path('avd_results', views.avd_results, name='avd_results'),
    path('ERROR/', views.ERROR, name='ERROR'),
]

uploads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django_mysql.models import ListCharField
from django.db.models import CharField



class Link(models.Model):
    link_text = models.CharField(max_length=200)
    author = models.ForeignKey(User, default=None,blank=True, on_delete=models.PROTECT, null = True)
    firstChar = models.CharField(max_length=1, blank=True, null=True)
    fileSize = models.CharField(max_length=200, blank=True, null=True)
    sha256 = models.CharField(max_length=200, blank=True, null=True)
    VT_permallink = models.CharField(max_length=100, blank=True, null=True)
    VT_sha1 = models.CharField(max_length=100, blank=True, null=True)
    VT_responseCode = models.CharField(max_length=100, blank=True, null=True)
    VT_resource = models.CharField(max_length=100, blank=True, null=True)
    VT_scanId = models.CharField(max_length=100, blank=True, null=True)
    VT_msg = models.CharField(max_length=100, blank=True, null=True)
    VT_sha256 = models.CharField(max_length=100, blank=True, null=True)
    VT_md5 = models.CharField(max_length=100, blank=True, null=True)
    jsonFile = models.FileField(blank = True, null = True, upload_to='Static')
    certFile = models.FileField(blank = True, null = True, upload_to='Certificate')
    VTFile = models.FileField(blank = True, null = True, upload_to='VirusTotal')
    URLSFile = models.FileField(blank = True, null = True, upload_to='URLS')
    TrackingURLSFile = models.FileField(blank = True, null = True, upload_to='Tracking_URLS')
    privacylink = models.CharField(max_length=200, blank=True, null=True)
    privacyText = models.CharField(max_length=10000, blank=True, null=True)
    smaliList = ListCharField(
        base_field=CharField(max_length=50),
        size=30,
        max_length=(50 * 50),  # 6 * 10 character nominals, plus commas
        blank = True,
        null = True
    )

class Document(models.Model):
    docfile = models.FileField(upload_to='APK_List')

    #rating = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.link_text


# Create your models here.

uploads/forms.py
from django import forms
from . import models

class CreateLink(forms.ModelForm):
    class Meta:
        model = models.Link
        fields = ['link_text']

class DocumentForm(forms.Form):
    docfile = forms.FileField(label='Select a file')

uploads/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from .models import Link
from . import forms
from django.core.files import File
from .functions import *
from .playStore import *
from .download_apk import *
from .adbFunctions import *
from .adb_Functions import *
from .trackinglibraries import *
from .machineLearningFunctions import *
import json
import mimetypes
import shutil
import subprocess
from .apk import *
from .apk_decompiler import *
from os import chdir, system
from django.contrib.auth.decorators import login_required
import sys
from io import BytesIO
from .certificate_Functions import *
#from OpenSSL import SSL
import time
import re
from django.core.files.base import ContentFile
from .filters import *
import html2text
from .models import Document
from .filepaths import *


#This is just a class that contains variables that store information regarding the static and meta-info analysis of an APK
#See the "function.py" file for the class definition


#This is a placeholder View for the running of the emulator
def emulator(request):

    device = "This is a placeholder - Emulator is currently not functioning"

    #Returns the mysite\uploads\templates\uploads\emulator.html file and parses 'device' as an argument
    return render(request, 'uploads/emulator.html', {'appID': device} )


#This simply displays the "download" page
def detail(request):
    link = get_object_or_404(Link, pk=link_id)
    return render(request, 'uploads/download.html', {'link': link})

#This function will download the VirusTotal JSON results to the users computer
#It is used in mysite\uploads\templates\uploads\download.html on the "VirusTotal" download button
def download_VirusTotal(request):
    #Gets the title of the app that was just analysed from the request

    val = request.POST.get('appCode', False);

    instanceID = request.POST.get('instanceID', False);
    test = request.POST

    obj = Link.objects.get(id=int(instanceID))
    VTFilePath = obj.VTFile.path
    print(VTFilePath)


    #Because VirusTotal results are stored in the format appID + "VirusTotal" as a txt file, appIDVT is the name of the corresponding VirusTotal results file
    appIDVT = val+"VirusTotal.txt"

    #This is the path to the VirusTotal results file
    fl_path = obj.VTFile.path

    #opened file
    fl = open(fl_path, 'r')

    #determines the MIME type of the file
    mime_type, _ = mimetypes.guess_type(fl_path)
    print("MIME:")
    print(mime_type)

    #Returns the file
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % appIDVT
    return response

#This function will download the Static and Meta-info JSON results to the users computer
#It is used in mysite\uploads\templates\uploads\download.html on the "Static and Meta-Info" download button
def download_JSONfile(request):

    val = request.POST.get('appCode', False);
    Sha256 = request.POST.get('Sha256', False);
    #appID is the total file name
    appID = val+"JSONFile.txt"

    instanceID = request.POST.get('instanceID', False);
    obj = Link.objects.get(id=int(instanceID))
    jsonFilePath = obj.jsonFile.path

    #fl_path is the path to the file
    fl_path = jsonFilePath
    filename = 'json.txt'
    fl = open(fl_path, 'r')

    #Returns the correct file and mime_type of the file upon clicking the "download" button
    mime_type, _ = mimetypes.guess_type(fl_path)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

#This function will download the Certificate info results to the users computer
#It is used in mysite\uploads\templates\uploads\download.html on the "Static and Meta-Info" download button
def download_Certfile(request):

    val = request.POST.get('appCode', False);
    #appID is the file name of the just analyzed APK
    appID = val+"CertFile.txt"

    instanceID = request.POST.get('instanceID', False);
    obj = Link.objects.get(id=int(instanceID))
    certFilePath = obj.certFile.path

    #path of the certificate file for the relevant APK
    fl_path = certFilePath
    filename = appID

    fl = open(fl_path, 'r')

    #Returns the correct file and mime_type of the file upon clicking the "download" button
    mime_type, _ = mimetypes.guess_type(fl_path)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

def download_PrivacyPolicyText(request):

    val = request.POST.get('appCode', False);
    #appID is the file name of the just analyzed APK
    print("val:")
    print(val)
    appID = val+".txt"
    print("appID: "+appID)

    instanceID = request.POST.get('instanceID', False);
    obj = Link.objects.get(id=int(instanceID))


    filename = appID
    policyPATH = returnPolicyPath(val)
    fl = open(policyPATH, 'r')

    #Returns the correct file and mime_type of the file upon clicking the "download" button
    mime_type, _ = mimetypes.guess_type(policyPATH)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

def download_URLRequests(request):
    val = request.POST.get('appCode', False);
    #appID is the file name of the just analyzed APK
    print("val:")
    print(val)
    apkCode = val
    filename = apkCode +"_requested_urls.txt"

    requestedURLSPath = returnURLSRequestedPath(apkCode)
    fl = open(requestedURLSPath, 'r')

    #Returns the correct file and mime_type of the file upon clicking the "download" button
    mime_type, _ = mimetypes.guess_type(requestedURLSPath)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

def download_SuspiciousURLRequests(request):
    val = request.POST.get('appCode', False);
    #appID is the file name of the just analyzed APK
    print("val:")
    print(val)
    apkCode = val
    filename = apkCode +"suspicious_requested_urls.txt"

    requestedURLSPath = returnURLSRequestedSharingPath(apkCode)
    fl = open(requestedURLSPath, 'r')

    #Returns the correct file and mime_type of the file upon clicking the "download" button
    mime_type, _ = mimetypes.guess_type(requestedURLSPath)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response


#Upon submitting an APK for analysis, the "results" function is called.
#This function will conduct all the static, meta-info and run the emulator.
#Currently, it just conducts the static and meta-info collection,
#however, in the future it will use an emulator to conduct dynamic analysis

def staticANDprivacyAnalysis(apkCode, instance, jsonClass):
    apkPATH = returnAPKPath(apkCode)
    zipPATH = returnAPKZIP(apkCode)
    apkFolder = filepaths_APKFolder
    policyPATH = returnPolicyPath(apkCode)
    apkFolderCD = filepaths_returnAPKPathCD
    manifestPath  = returnAPKManifestPath(apkCode)
    requestedURLSPath = returnURLSRequestedPath(apkCode)
    jsonPath = returnAPKJSON(apkCode)
    VirusTotalPath = returnAPKVirusTotal(apkCode)
    CertPath = returnAPKCERT(apkCode)
    mitmdumpsPath = returnAPKMitmdumps(apkCode)

    #print(getTextFromHTML("https://www.bodygrooveondemand.com/privacy")[0])
    #Run VirusTotal Scan, returns results in a list called 'VirusTotalResults'
    print("Doing VT Scan - It will be a minute!")
    VirusTotalResponse = vt_scan(apkCode)
    VirusTotalResults  = VirusTotalResponse.get('list')
    CheckVTLater  = VirusTotalResponse.get('checkVTLater')


    #decompiles APK using apktool, the output is just a folder
    decompileAPK(apkCode, apkFolder, apkFolderCD)

    #If a manifest file can be found in the resulting folder, collect permissions and services from the file
    #Inserts the results in to a list, which will then be displayed in the JSON file
    if(os.path.exists(manifestPath)):
        theseUsesPermissions = usesPermissionsFromXML(manifestPath) #collects permissions
        thesePermissions = permissionsFromXML(manifestPath) #collections permissions
        serviceList = servicesFromXML(manifestPath) #collects service permissions
    else:
        #If the file can't be found, the JSON file will display the below text
        theseUsesPermissions = "Can't decompile properly"
        thesePermissions ="Can't decompile properly"
        serviceList = "Can't decompile properly"


    try:
        #Will try and connect to the Google Play website to scrape the meta-info database
        #Saves the information in the form of a list
        metaInformation = metaFromWebsite(apkCode)
        AndroidWebCantConnect = False
    except Exception as e:
        print("Error in metaFromWebsite()")
        print(e)
        print("Can't connect to android website-------------------")
        metaInformationText = "Can't connect to android website"
        AndroidWebCantConnect = True


    if AndroidWebCantConnect == False:
        privacyPolicyResults = getTextFromHTML(metaInformation[3].get("Privacy Policy"))
    else:
        privacyPolicyResults = ['NA', True]

    try:
        CSVPermissionsResults = usesPermissionsForCSV(manifestPath)
    except:
        CSVPermissionsResults = None


    smaliDirectory = returnSmaliKey(returnSmaliTuplDict(), getLibrariesDirectories(apkCode))

    smaliFiles = getLibrariesSmali(apkCode)


    #Will find the file_size of the APK
    APKfilesize = file_size(apkPATH)
    sha256Calculated = getSha(apkCode)
    instance.link_text = apkCode
    instance.fileSize = APKfilesize
    instance.sha256 = sha256Calculated
    instance.firstChar = returnZ(instance.link_text)

    instance.VT_permallink = VirusTotalResults[0]
    instance.VT_sha1 = VirusTotalResults[1]
    instance.VT_resource = VirusTotalResults[2]

uploads/templates/uploads/avd.html
{% extends "uploads/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>What is the android handle for your APK?</h2>
<body>
<form class = "site-form" action="{% url 'uploads:avd_results' %}" method = "post">
  {% csrf_token %}

  <input type = "submit" value = "Analyse">
</form>

<text> Analysis will take a few minutes, please be patient... </text>
</body>
{% endblock content %}

uploads/templates/uploads/avd_results.html
{% extends "uploads/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>You are in AVD Results</h2>
<body>
</body>
{% endblock content %}

uploads/templates/uploads/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/stylesheet.css" />


    <style>

    body {
      background: #fafafa;
      color: #111111;
      margin-top: 5rem;
    }

    h1, h2, h3, h4, h5, h6 {
      color: #444444;
    }
    h1 {text-align: center;}

    ul {
      margin: 0;
    }

    .bg-steel {
      background-color:#3c6a6d;
    }

    .site-header .navbar-nav .nav-link {
      color: #ffffff;
    }

    .site-header .navbar-nav .nav-link:hover {
      color: #ffffff;
    }

    .site-header .navbar-nav .nav-link.active {
      font-weight: 500;
    }

    .content-section {
      background: #ffffff;
      padding: 10px 20px;
      border: 1px solid #dddddd;
      border-radius: 3px;
      margin-bottom: 20px;
    }

    .article-title {
      color: #444444;
    }

    a.article-title:hover {
      color: #428bca;
      text-decoration: none;
    }

    .article-content {
      white-space: pre-line;
    }

    .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
    }

    .article-metadata {
      padding-bottom: 1px;
      margin-bottom: 4px;
      border-bottom: 1px solid #e3e3e3
    }

    .article-metadata a:hover {
      color: #333;
      text-decoration: none;
    }

    .article-svg {
      width: 25px;
      height: 25px;
      vertical-align: middle;
    }

    .account-img {
      height: 125px;
      width: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
    }

    .account-heading {
      font-size: 2.5rem;
    }

    /* Teams CSS */


    .pricing .card {
      border: none;
      border-radius: 1rem;
      transition: all 0.2s;
      box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .pricing hr {
      margin: 1.5rem 0;
    }

    .pricing .card-title {
      margin: 0.5rem 0;
      font-size: 0.9rem;
      letter-spacing: .1rem;
      font-weight: bold;
    }

    .pricing .card-price {
      font-size: 3rem;
      margin: 0;
    }

    .pricing .card-price .period {
      font-size: 0.8rem;
    }

    .pricing ul li {
      margin-bottom: 1rem;
    }

    .pricing .text-muted {
      opacity: 0.7;
    }

    .pricing .btn {
      font-size: 80%;
      border-radius: 5rem;
      letter-spacing: .1rem;
      font-weight: bold;
      padding: 1rem;
      opacity: 0.7;
      transition: all 0.2s;
    }

/* Hover Effects on Card */

@media (min-width: 992px) {
  .pricing .card:hover {
    margin-top: -.25rem;
    margin-bottom: .25rem;
    box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.3);
  }
  .pricing .card:hover .btn {
    opacity: 1;
  }
}



.site-footer
{
  background-color:#3c6a6d;
  padding:45px 0 20px;
  font-size:15px;
  line-height:24px;
  color:#bff3dd;
}
.site-footer hr
{
  border-top-color:#bbb;
  opacity:0.5
}
.site-footer hr.small
{
  margin:20px 0
}
.site-footer h6
{
  color:#fff;
  font-size:16px;
  text-transform:uppercase;
  margin-top:5px;
  letter-spacing:2px
}
.site-footer a
{
  color:#737373;
}
.site-footer a:hover
{
  color:#3366cc;
  text-decoration:none;
}
.footer-links
{
  padding-left:0;
  list-style:none
}
.footer-links li
{
  display:block
}
.footer-links a
{
  color:#bff3dd
}
.footer-links a:active,.footer-links a:focus,.footer-links a:hover
{
  color:#ffffff;
  text-decoration:none;
}
.footer-links.inline li
{
  display:inline-block
}
.site-footer .social-icons
{
  text-align:right
}
.site-footer .social-icons a
{
  width:40px;
  height:40px;
  line-height:40px;
  margin-left:6px;
  margin-right:0;
  border-radius:100%;
  background-color:#33353d
}
.copyright-text
{
  margin:0
}
@media (max-width:991px)
{
  .site-footer [class^=col-]
  {
    margin-bottom:30px
  }
}
@media (max-width:767px)
{
  .site-footer
  {
    padding-bottom:0
  }
  .site-footer .copyright-text,.site-footer .social-icons
  {
    text-align:center
  }
}



    </style>
</head>
<body>
  <header class="site-header">
     <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
       <div class="container">
         <a class="navbar-brand mr-4" href="{% url 'Home' %}">App Garadyi</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarToggle">
           <div class="navbar-nav mr-auto">
             <a class="nav-item nav-link" href="{% url 'uploads:uploadHere' %}">Upload</a>
             <a class="nav-item nav-link" href="{% url 'database:databaseHome' %}">Database</a>

           </div>
           <!-- Navbar Right Side -->
           <div class="navbar-nav">
             <a class="nav-item nav-link" href="{% url 'account:view_login' %}">Login</a>
             <a class="nav-item nav-link" href="{% url 'account:view_logout' %}">Logout</a>
             <a class="nav-item nav-link" href="{% url 'account:view_signup' %}">Register</a>
             <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
           </div>
         </div>
       </div>
     </nav>
   </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-xl-12 align-self-center">
          <div class="card card-body">

          {% block content %}{% endblock %}
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


</body>
<br>
<br>
<br>
<br>
<br>

<footer class="site-footer">
     <div class="container">
       <div class="row">
         <div class="col-sm-12 col-md-6">
           <h6>About</h6>
           <p class="text-justify">This website performs privacy analysis on Google Play applications </p>

         </div>

         <div class="col-xs-6 col-md-3">
           <h6>Quick Links</h6>
           <ul class="footer-links">
             <li><a href="">How To Use</a></li>
             <li><a href="">Signup</a></li>
             <li><a href="">Organisations</a></li>
           </ul>
         </div>

         <div class="col-xs-6 col-md-3">
           <h6>Other</h6>
           <ul class="footer-links">
             <li><a href="">Privacy Policy</a></li>
             <li><a href="">Contact</a></li>
             <li><a href="">Why</a></li>
           </ul>
         </div>
       </div>
       <hr>
     </div>
     <div class="container">
       <div class="row">
         <div class="col-md-8 col-sm-6 col-xs-12">
           <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by Jake</p>
         </div>

       </div>
     </div>
</footer>


</html>

uploads/templates/uploads/download.html
{% extends "uploads/base.html" %}
{% block content %}

<h1>Your {{apkCode}} static and meta-info data is available for download here</h1>
<h2> YOU ARE IN LINK_ID {{instanceID}} ? </h2>

<body>
<form class = "site-form" action="{% url 'uploads:download_JSONfile' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>
</body>
<h1>Your Certificate file can be downloaded here </h1>
<body>
<form class = "site-form" action="{% url 'uploads:download_Certfile' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>
</body>
<h1>Your VirusTotal file can be downloaded here </h1>
<body>
<form class = "site-form" action="{% url 'uploads:download_VirusTotal' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>
</body>
<h1>Your Privacy Policy Text file can be downloaded here </h1>
<body>
<form class = "site-form" action="{% url 'uploads:download_PrivacyPolicyText' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>
<h1>URLS Requested can be downloaded here</h1>
<form class = "site-form" action="{% url 'uploads:download_URLRequests' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>

<h1>Tracking URLS Requested can be downloaded here</h1>
<form class = "site-form" action="{% url 'uploads:download_SuspiciousURLRequests' %}" method = "post">
  {% csrf_token %}
  <input type = "hidden" name="appCode" value={{apkCode}}>
  <input type = "hidden" name="instanceID" value={{instanceID}}>

  <input type = "submit" value = "Download">
</form>
</body>
{% endblock content %}

uploads/templates/uploads/emulator.html
{% extends "uploads/base.html" %}
{% block content %}
<h2>Emulator Information</h2>

<body>
<h1>Device: {{appID}}</h1>
<text> Analysis will take a few minutes, please be patient... </text>
</body>
{% endblock content %}

uploads/templates/uploads/error.html
{% extends "uploads/base.html" %}
{% block content %}
<h2>About</h2>

<body>
<text>Error downloading the APK - most likely it could not be found</text>
</body>
{% endblock content %}

uploads/templates/uploads/index.html
{% extends "uploads/base.html" %}
{% block content %}
{% if latest_link_list %}
    <ul>
    {% for link in latest_link_list %}
      <li><a href="{% url 'uploads:detail' link.id %}">{{ link.link_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No links are available.</p>
{% endif %}
{% endblock content %}

uploads/templates/uploads/list.html
{% extends "uploads/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
        <!-- List of uploaded documents -->
        {% if documents %}
            All documents in the database:
            <ul>
                {% for document in documents %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "uploads:getFile" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ message }}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
    </body>
</html>
{% endblock content %}

uploads/templates/uploads/uploads.html
{% extends "uploads/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>What is the android handle for your APK?</h2>
<body>
<form class = "site-form" action="{% url 'uploads:results' %}" method = "post">
  {% csrf_token %}
  {{form}}
  <input type = "submit" value = "Analyse">
</form>
<h3> {{Analyse.type}} </h3>
<text> Analysis will take a few minutes, please be patient... </text>
</body>
{% endblock content %}

uploads/templates/uploads/uploadsManyAPK.html
{% extends "uploads/base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>When you click analyse, it will analyse all the apk files listed in your text file</h2>
<body>
<form class = "site-form" action="{% url 'uploads:results' %}" method = "post">
  {% csrf_token %}
  {{form}}
  <input type = "submit" value = "Analyse">
</form>
<h3> {{Analyse.type}} </h3>
<text> Analysis will take a while, please be patient... </text>
</body>
{% endblock content %}